#!/usr/bin/env bash
# a bash script that transfers a file from client to a server
if [ "$#" -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

file="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

export SCP_OPTIONS="-o StrictHostKeyChecking=no"

scp -i "$ssh_key" "$SCP_OPTIONS" "$file" "$username"@"$server_ip":~/
