#!/usr/bin/env bash
# Installs nginx on a web-server
sudo apt update
sudo apt install -y nginx

echo "server {
	listen 80 default_server;

	root /var/www/html;
	index index.html;

	server_name _;

	location / {
		echo 'Hello World!';
	}
}" > /etc/nginx/sites-available/default

sudo service nginx restart
