#!/usr/bin/env bash
# Installs nginx on a web-server
sudo apt update
sudo apt install -y nginx

echo "server {
    listen 80;
    
    location / {
        return 200 'Hello World!';
    }
}" > /etc/nginx/sites-available/default

sudo service nginx start
