#!/usr/bin/env bash
# configures nginx server to redirect to another page
sudo apt update
sudo apt install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i '/server_name _;/a \\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/youtube.com\/;\n\t}' /etc/nginx/sites-available/default

sudo service nginx restart
