#!/usr/bin/env bash
# configures nginx server to redirect to another page
sudo apt update
sudo apt install -y nginx

echo "server {
    listen 80;

    location / {
        return 200 'Hello World!';
    }
}" > /etc/nginx/sites-available/default

sudo sed -i '/location \/ {/a \\tlocation \/redirect_me {\n\treturn 301 https:\/\/youtube.com\/;\n\t}' /etc/nginx/sites-available/default

sudo service nginx start
