#!/usr/bin/env bash
# configures nginx server to redirect to another page
sudo apt update
sudo apt install -y nginx

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html

echo "server {
    listen 80;

    location / {
        return 200 'Hello World!';
    }
}" > /etc/nginx/sites-available/default

sudo sed -i '/listen 80;/a \\n    location \/redirect_me {\n\treturn 301 https:\/\/youtube.com\/;\n    }\n    error_page 404 \/404.html;\n    location = \/404.html {\n\troot /usr/share/nginx/html;\n\tinternal;\n    }' /etc/nginx/sites-available/default

sudo service nginx restart
sudo service nginx reload
