#!/usr/bin/env bash
# configures nginx server to have custom error 404 page
sudo apt update
sudo apt install -y nginx

sudo service nginx start

echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html

sudo sed -i "/location \/ {/a \\\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/youtube.com\/;\n\t}\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}" /etc/nginx/sites-available/default

sudo service nginx restart
sudo service nginx reload
