#!/usr/bin/env bash
# configures nginx server to have a custom 404 page
sudo apt update
sudo apt install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo sed -i "/location \/ {/a \\\t\terror_page 404 \/404.html;" /etc/nginx/sites-available/default

sudo service nginx restart
