#!/usr/bin/env bash
# install and configures HAproxy
sudo apt update
sudo apt install -y software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt install -y haproxy=2.8.\*

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.cp

sudo sed -i "/errorfile 504 \/etc\/haproxy\/errors\/504.http/a \\\nfrontend http_front\n\tbind *:80\n\tmode http\n\tdefault_backend http_back\n\nbackend http_back\n\tbalance roundrobin\n\tserver 148962-web-01 100.25.140.168:80 check\n\tserver 148962-web-02 54.208.180.150:80 check" /etc/haproxy/haproxy.cfg

sudo ln -s /usr/sbin/haproxy /etc/init.d/haproxy

sudo service haproxy restart
