#!/usr/bin/env bash
# installs and configures haproxy
sudo apt update
sudo apt install -y haproxy

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 148962-web-01 100.25.140.168:80 check
    server 148962-web-02 54.208.180.150:80 check
EOF

sudo systemctl enable haproxy
sudo systemctl restart haproxy
