#!/usr/bin/env bash
# reconfiguring nginx server to listen to port 80
sudo service nginx start
sudo sed -i 's/listen 8080 default_server;/listen 80 default_server;/g' /etc/nginx/sites-enabled/default
sudo sed -i 's/listen \[::\]:8080 default_server ipv6only=on;/listen \[::\]:80 default_server;/g' /etc/nginx/sites-enabled/default
sudo sed -i 's/ ipv6only=on//g' /etc/nginx/sites-available/default
sudo service nginx restart
