#!/usr/bin/env bash
# reconfiguring nginx server to listen to port 80
sudo service nginx start
sudo sed -i 's/8080/80/g; s/ ipv6only=on//g' /etc/nginx/sites-enabled/default
sudo service nginx restart
