#!/usr/bin/env bash
# reconfiguring nginx server to listen to port 80 and stops nginx from running
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enables/default
sudo service nginx restart
sudo kill -9 "$(cat /run/nginx.pid)"
