#!/usr/bin/env bash
# displays the content of the file /etc/passwd
# displays the username, user id, and home directory for the user
filename=/etc/passwd
while read -r line
do
	username=$(echo "$line" | cut -d: -f1)
	userid=$(echo "$line" | cut -d: -f3)
	homepath=$(echo "$line" | cut -d: -f6)

	echo "$username:$userid:$homepath"
done < "$filename"
