#!/usr/bin/env bash
# bash script that configures nginx to run as nginx user
sudo sed -i 's@#user www-data@user nginx@g' /etc/nginx/nginx.conf
sudo sed -i 's@80 default_server@8080 default_server@g' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
pkill -9 apache
sudo service nginx restart
