#!/usr/bin/env bash
# a script that fix nginx to run nginx as nginx user and listens on port 8080
sudo sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
chmod 777 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill -9 apache2
sudo -u nginx service nginx restart
